describe("Test Suites 1", { scrollBehavior: "center" }, () => {
  beforeEach(() => {
    cy.clearCookies();
    cy.viewport("macbook-13");
    cy.visit("/");
    cy.wait(2000);
  });

  it("Search flow", () => {
    //Given I am in the Youtube Music home page
    //When I click Search button on navigation bar
    cy.get(".ytmusic-search-box").contains("Telusuri").click();

    //And I type 'It Don't Matter Jacob Collier'
    cy.get('input[id="input"]').type("it don't matter Jacob Collier{enter}");

    //Then the result is appear
    cy.get(".ytmusic-shelf-renderer")
      .contains("It Don't Matter (feat. JoJo)")
      .should("be.visible", { multiple: true });
  });

  it("Quick selection in “Dengarkan lagi” slide menu", () => {
    // Given I am accessing the Youtube Music
    // When the page loaded
    // Then I can see the 'Pilihan Cepat' slide menu
    cy.get(".ytmusic-carousel-shelf-renderer:eq(0)")
      .contains("Pilihan cepat")
      .should("be.visible");

    // And I can click one of them
    cy.get('.ytmusic-carousel > div > div [title="Sang Dewi"]:eq(0)').click();
  });

  it("Homepage playlists menu", () => {
    // Given I am in the Youtube Music homepage
    // When I scroll down the page
    cy.scrollTo("0%", "20%");
    cy.get(".ytmusic-carousel-shelf-renderer")
      .contains("Playlist Indonesia")
      .scrollIntoView({ duration: 500 })
      .should("be.visible");
    // Then I can see playlists generated by Youtube

    // And I can click one of them
    cy.get('.ytmusic-carousel ul:eq(1) [role="listitem"]:eq(0)')
      .should("be.visible")
      .and("not.be.disabled")
      .click();

    cy.url().should("include", "playlist?");
  });

  it("Playing the music", () => {
    //Given I am searching 'It Don't Matter Jacob Collier'
    cy.get(".ytmusic-search-box").contains("Telusuri").click();
    cy.get('input[id="input"]').type("it don't matter Jacob Collier{enter}");

    //When I see the top result
    //And there is the song
    cy.contains("Hasil teratas").should("be.visible");
    cy.get(".ytmusic-shelf-renderer")
      .contains("It Don't Matter (feat. JoJo)")
      .should("be.visible", { multiple: true });

    //Then I can click it
    // And the music will start
    cy.get(".ytmusic-shelf-renderer")
      .contains("It Don't Matter (feat. JoJo)")
      .click();

    cy.get('[slot="player-bar"]').should("be.visible");
    cy.wait(20000);
  });

  it("Pausing the music", () => {
    //Given I am playing the music
    cy.play_music();

    //And there is a music player in footer side
    //When I click the pause button
    // Then the music will be paused
    cy.get("#play-pause-button").click();
    cy.get("#play-pause-button").should("have.attr", "Title", "Putar");
  });
});
